FROM openjdk:17-jdk

ARG DB_URL
ENV DB_URL ${DB_URL}

ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}

ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}

ARG ACCESS_KEY
ENV ACCESS_KEY ${ACCESS_KEY}

ARG REDIS_HOST
ENV REDIS_HOST ${REDIS_HOST}

ARG AWS_ACCESS_KEY
ENV AWS_ACCESS_KEY ${AWS_ACCESS_KEY}

ARG SECRET_KEY
ENV SECRET_KEY ${SECRET_KEY}

ARG LOGIN_URL
ENV LOGIN_URL ${LOGIN_URL}

ARG DAEDONG_SECRET_KEY
ENV DAEDONG_SECRET_KEY ${DAEDONG_SECRET_KEY}

ARG PICK_SECRET_KEY
ENV PICK_SECRET_KEY ${PICK_SECRET_KEY}

ARG ADMIN_ID
ENV ADMIN_ID ${ADMIN_ID}

ARG SECRET
ENV SECRET ${SECRET}

ARG JAR_FILE=build/libs/*.jar

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=doker", "-jar", "app.jar"]