spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  spring:
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      show-sql: true
      hibernate:
        ddl-auto: update
  redis:
    host: localhost
    port: 6379
jwt:
  header: Authorization
  prefix: Bearer
  secret: lhjljlasndflasjdkfasdkfnasdasjidkflajsdkfahsdfjkafewfawefwaefeawfw
  accessExpiration: 604800

server:
  port: 8080

